const APIURLConstants = {
    PING: '/Home/Ping',
    GET_SHAREPOINT_ACCESS_TOKEN: '/Home/GetSharePointToken',
    SHAREPOINT_BASE_URL: 'https://graph.microsoft.com/v1.0/drives',

    //... Auth
    SIGNOUT: '/Auth/SignOut',
    GET_APP_DETAILS: '/Auth/GetAppDetails',
    GET_CONFIGS: '/Auth/GetConfigs',
    GET_CUSTOM_LOGIN_DETAILS: (Id, name) => `/Auth/GetCustomLoginDetails?Id=${Id}&name=${name}`,
    GET_CUSTOM_LOGIN_USERS: '/Auth/GetCustomLoginUsers',
    //...Common
    GET_USERS_LIST_BY_ROLE_NAME: (roleName) => `/Common/GetUsersListByRole?roleName=${roleName}`,
    GET_LEAGUES: '/Common/GetLeague',
    GET_SCHEDULES: '/Common/GetSchduleInfo',
    GET_COSTTYPES: '/Common/GetCostType',

    GET_PARTNER_BY_TYPE: (id) => `/Common/GetPartnerByType?partnerTypeId=${id}`,
    GET_PARTNER_BY_INVENTORY: (leagueId, mediaTypeId, regionIds) => `/Common/GetPartnerByInventory?leagueId=${leagueId}&mediaTypeId=${mediaTypeId}&regionIds=${regionIds}`,
    GET_PARTNER_BY_INVENTORY_PLANNING: (leagueId, mediaTypeId, regionIds) => `/Common/GetPartnerByInventoryPlanning?leagueId=${leagueId}&mediaTypeId=${mediaTypeId}&regionIds=${regionIds}`,
    GET_NETWORKS: (partnerId) => `/Common/GetNetwork?partnerId=${partnerId}`,
    GET_NETWORK_BY_REGION: (partnerId, regionId, mediaTypeId) => `/Common/GetNetworkByRegion?partnerId=${partnerId}&regionId=${regionId}&mediaTypeId=${mediaTypeId}`,
    GET_NETWORK_BREAK_POSITIONS: '/Common/GetNetworkBreakPositions',

    GET_UNIT_TYPES: (id) => `/Common/GetUnitTypes?mediaTypeId=${id}`,
    GET_UNIT_SIZES: (id) => `/Common/GetUnitSizes?unitTypeId=${id}`,
    GET_REGIONS: '/Common/GetRegion',
    GET_SEASONS_BY_LEAGUE:(id) => `/Common/GetSeason?leagueId=${id}`,
    GET_MEDIATYPES: '/Common/GetMediaType',
    GET_COUNTRIES_REGION: (regionId) => `/Common/GetCountries?region=${regionId}`,
    GET_COUNTRIES_BY_REGIONIDS: (regionIds) => `/Common/GetCountriesByRegions?regionIds=${regionIds}`,
    GET_RATES: '/xyz',
    GET_PROGRAM: (id) => `/Common/GetProgram?programTypeId=${id}`,
    GET_CHANNELS: (id, name) => `/Common/GetChannelsByPartner?partnerId=${id}&mediaTypeName=${name}`,
    GET_LOOKUP_By_ID: (id) => `/Common/GetLookupById?Id=${id}`,
    BILL_BY_ID: 310,
    GET_LOOKUPS: '/Common/GetLookup',
    GET_SEASONS: '/Common/GetSeason',
    GET_CURRENT_SEASONS_INFO: '/Common/GetCurrentSeasonsInfo',
    INS_UPD_SEASON: '/Common/InsUpdSeason',
    GET_REPORT_URL: (name, setting) => `/Common/GetReportConfig?name=${name}&setting=${setting}`,
    GET_USER_PREFERENCE_BY_MODULE: (typeId, leagueId) => `/Common/GetSavedSearchUserPreferences?typeId=${typeId}&leagueId=${leagueId}`,
    GET_MEDIUM: (id) => `/Common/GetMedium?mediumId=${id}`,
    GET_ASSETS_BY_INVENTORY: (leagueId, MarketTypeId, VenturizeId, MediaType, NetworkId) => `/Common/GetAssetByInventory?leagueId=${leagueId}&marketTypeId=${MarketTypeId}&venturizedId=${VenturizeId}&mediumId=${MediaType}&networkId=${NetworkId}`,
    GET_ASSETS_BY_INVENTORY_PLANNING: (leagueId, MarketTypeId, VenturizeId, MediaType, PartnerId) => `/Common/GetAssetByInventoryPlanning?leagueId=${leagueId}&marketTypeId=${MarketTypeId}&venturizedId=${VenturizeId}&mediumId=${MediaType}&partnerId=${PartnerId}`,
    GET_ASSETS: (leagueId, MarketTypeId, VenturizeId, MediaType) => `/Common/GetAssetDetails?leagueId=${leagueId}&marketTypeId=${MarketTypeId}&venturizedId=${VenturizeId}&mediumId=${MediaType}`,
    GET_ASSETS_PARENT: (leagueId, MarketTypeId, VenturizeId, MediaType) => `/Common/GetAssetParentDetails?leagueId=${leagueId}&marketTypeId=${MarketTypeId}&venturizedId=${VenturizeId}&mediumId=${MediaType}`,
    GET_EPISODES: (assetId) => `/Common/GetEpisodeByAsset?assetId=${assetId}`,
    GET_ISCI_LIST: (LeagueId, CampaignOrAdvertiserIdIds) => `/Common/GetISCIsList?LeagueId=${LeagueId}&CampaignOrAdvertiserIdIds=${CampaignOrAdvertiserIdIds}`,
    GET_ISCIS_LIST: '/Common/GetISCIList',
    INS_UPD_ISCI_DETAILS: '/Common/InsUpdISCIinfo',

    ADD_UPDATE_SAVED_PREFERENCE: '/Common/AddUpdateUserPreferences',
    DELETE_USER_SAVED_PREFERENCE: (id) => `/Common/DeleteSavedSearchUserPreferences?id=${id}`,
    GET_BRANDS:(id)=>`/Common/GetAdvertiserProduct?AdvertiserId=${id}`,

    //...Inventory
    //GET_INVENTORY: '/Inventory/GetInventory',
    GET_INVENTORY: `/Inventory/GetInventoryGroup`,
    GET_FREQUENCIES: '/Common/GetFrequencies',
    GET_DAYS: '/Common/GetDays',
    GENERATE_SCHEDULES_WITH_INVENTORY: '/Inventory/GenerateInventorySchedules',
    GET_SCHEDULES_BY_INVENTORY: '/Inventory/GetScheduleByInventory',
    GET_INVENTORY_UNIT: (inventoryID) => `/Inventory/GetInventoryUnit?inventoryId=${inventoryID}`,
    GET_INVENTORY_SCHEDULE: (id) => `/Inventory/GetInventorySchedule?inventoryId=${id}`,
    SAVE_INVENTORY_UNIT: '/Inventory/SaveInventoryUnit',
    DELETE_INVENTORY_UNIT: '/Inventory/DeleteInventoryUnit',
    GET_COPY_SCHEDULE_BREAKUPS: (id) => `/Inventory/GetCopyScheduleBreakUps?inventoryId=${id}`,
    SAVE_COPY_SCHEDULE: '/Inventory/SaveCopySchedule',
    GET_MONTHLY_SCHEDULE: (id) => `/Inventory/GetMonthlyScheduleGroup?inventoryId=${id}`,
    INSERT_MONTHLY_SCHEDULE: '/Inventory/InsertMonthlySchedule',
    SAVE_INVENTORY_DEAL: '/Inventory/SaveInventoryDeal',
    SAVE_INVENTORY: '/Inventory/SaveInventory',
    DELETE_INVENTORY: '/Inventory/DeleteInventory',
    GET_INVENTORIES_BY_DEAL_ID: (id) => `/Inventory/GetInventorisByDealId?inventoryDealId=${id}`,
    CHECK_INVENTORY_SCHEDULE_BYDATE: (id, startDate, endDate) => `/Inventory/CheckInventoryScheduleByDate?inventoryId=${id}&startDate=${startDate}&endDate=${endDate}`,
    GET_DIGITAL_ADDITIONAL_INVENTORY_INFO: (inventoryId) => `/Inventory/GetDigitalAdditionalInventoryInfo?inventoryId=${inventoryId}`,
    GET_DIGITAL_ASSET_ADUNIT_MAPPING: (assetId) => `/Inventory/GetDigitalAssetAdUnitMapping?assetId=${assetId}`,
    SAVE_DIGITAL_ADDITIONAL_INVENTORY_INFO: '/Inventory/SaveDigitalAdditionalInventoryInfo',
    EDIT_SCHEDULE: '/Inventory/EditSchedule',
    DELETE_SCHEDULE: (id) => `/Inventory/DeleteSchedule?scheduleId=${id}`,
    //DELETE_SCHEDULE: '/Inventory/DeleteSchedule',
    GET_EPISODE_LIST:`/Inventory/GetEpisodeList`,

    //Planning
    GET_DEALS: `/Planning/BudgetByDeal`,
    Get_Media_Plans: (id, year, leagueId) => `/Planning/MediaPlans?campaignOrAdvertiserId=${id}&year=${year}&leagueId=${leagueId}`,
    Get_Media_Plans_Criteria: `/Planning/MediaPlans`,
    SAVE_MEDIA_PLAN: '/Planning/SaveMediaPlan',
    GET_ADDITIONAL_DEALINFO: (id) => `/Planning/GetAdditionalDealInfo?id=${id}`,
    SAVE_ADDITIONAL_DEAL_INFO: '/Planning/AddUpdateAdditionalInfo',
    GET_AVAILABLE_SCHEDULE_UNITS: `/Planning/GetEpisodeWithAvailableInventory`,
    GET_AVAILABLE_SCHEDULE_AND_UNITS_COUNT: `/Planning/GetAvailableEpisodeUnitsCount`,
    SAVE_MEDIA_PLAN_BUDGETS : `/Planning/SaveMediaPlanBudgets`,
    Get_Media_Plans_Budgets: (id) => `/Planning/MediaPlanBudgets?id=${id}`,
    SPLIT_SCHEDULE_UNIT : '/Planning/SplitScheduleUnit',
    MERGE_SCHEDULE_UNITS: '/Planning/MergeScheduleUnits',
    CHANGE_UNIT_COST_TYPE: '/Planning/ChangeUnitCostType',
    GET_CAMPAIGN_MEDIA_PLANS: (id, year) => `/Planning/GetCampaignMediaPlans?leagueId=${id}&year=${year}`,
    Get_Media_Plan_Medium:(planId) => `/Planning/GetMediaPlanMedium?planId=${planId}`,
    Save_Media_Plan_Medium: '/Planning/SaveMediaPlanMedium',
    VALIDATE_UNITS_AND_PLAN: '/Planning/ValidateSalesInventory',
    VALIDATE_CAMPAIGN_UNITS_AND_PLAN: '/Planning/ValidateCampaignInventory',
    GET_DIGITAL_UNIT_SIZES: (inventoryId, IsCampaignPlanning) => `/Planning/GetDigitalUnitSizes?InventoryId=${inventoryId}&IsCampaignPlanning=${IsCampaignPlanning}`,
    GET_DIGITAL_DEFAULT_UNIT_SIZES: (inventoryId, IsCampaignPlanning) => `/Planning/GetDigitalDefaultUnitSizes?InventoryId=${inventoryId}&IsCampaignPlanning=${IsCampaignPlanning}`,
    Get_Media_Plan_Partners: (id, year) => `/Planning/GetMediaPlanPartners?leagueId=${id}&year=${year}`,
    DELETE_MEDIAPLAN_BUDGET: (id) => `/Planning/DeleteMediaPlanBudget?planBudgetId=${id}`,
    GET_INVENTORY_ASSETS: '/Planning/GetAssetDetails',

    //...RateCard
    GET_RATE_CARDS: (leagueId, rateCardId) => `/RateCard/GetRateCard?leagueId=${leagueId}&rateCardId=${rateCardId}`,
    GET_RATE_CARDS_RECORDS: '/RateCard/GetRateCardRecords',
    INSERT_RATE_CARD: '/RateCard/InsertRateCard',
    GET_RATES_BY_INVENTORY_ID: (id) => `/RateCard/GetRateCardByInventoryId?inventoryId=${id}`,
    
    /// TRAFFICKING
    GET_SCHEDULE: `/Trafficking/GetSchedule`,
    GET_SCHEDULE_AD_UNIT: (id,ros) => `/Trafficking/GetTraffickingData?ScheduleId=${id}&isROS=${ros}`,
    GET_NETWORK_BREAK_AND_POSITION: (leagueId, networkId, marketTypeId) => `/Trafficking/GetNetworkBreakAndPosition?leagueId=${leagueId}&networkId=${networkId}&marketTypeId=${marketTypeId}`,
    SAVE_TRAFFICKING_DATA: `/Trafficking/SaveTraffickingData`,
    SAVE_TRAFFICKING_STATUS: `/Trafficking/UpdateTraffickingStatus`,
    FILTER_TRAFFICKING_DATA:`/Trafficking/GetTraffickScheduleCopyData`,
    SAVE_SCHEDULE_COPY_DATA:`/Trafficking/SaveTraffickScheduleCopyData`,
    GENERATE_TRAFFICK_LETTER: `/Trafficking/GenerateTrafficLetter`,
    MARK_AS_TRAFFICKED: '/Trafficking/MarkTraffiked',
    GET_REVISIONNUMBER: '/Trafficking/GetRevisionNumber',
    GET_TRAFFICKED_PARTNER: '/Trafficking/GetTraffickedPartner',
    GET_TRAFFICKED_ASSET: '/Trafficking/GetTraffickedAsset',
    GET_DIGITAL_SCHEDULE: `/Trafficking/GetDigitalSchedule`,
    DIGITAL_MEDIA_TRAFFICKING: '/Trafficking/UpdateDigitalMediaTraffickingStatus',

    //Campaigns
    Campaign_List: (leagueId) => `/Campaign/GetCampaignList?leagueId=${leagueId}`,
    AddCampaign: `/Campaign/AddUpdateCampaign`,
    ADD_UPDATE_CAMPAIGN_UNIT: `/Campaign/AddUpdateCampaignUnitInstructions`,
    GET_CAMPAIGN_UNIT_LIST: (id) => `/Campaign/GetCampaignListUnitInstructions?campaignId=${id}`,
    GET_EPISODES_BY_STARTDATE_ENDDATE: (startDate, endDate, campaignOrAdvertiserId, campaignUnitTypeId, campaignUnitInstructionId) => `/Campaign/GetEpisodesByStartDateEndDate?startDate=${startDate}&endDate=${endDate}&campaignOrAdvertiserId=${campaignOrAdvertiserId}&campaignUnitTypeId=${campaignUnitTypeId}&campaignUnitInstructionId=${campaignUnitInstructionId}`,
    SAVE_CAMPAIGN: `/Campaign/AddUpdateCampaign`,
    DOWNLOAD_INSTRUCTION_FILE: (campaignId, instructionId) => `/Campaign/DownloadInstructionFile?campaignId=${campaignId}&instrunctionId=${instructionId}`,

    GET_INVERTORY_SEARCH: `/Planning/GetInventorySearch`,
    SAVE_CAMPAIGN_MEDIA_PLAN_AND_UNITS: '/Planning/SaveMediaPlanDataAndProposedUnits',
    GET_MEDIA_PLAN_SUMMARY_LIST: '/Planning/GetPlanSummaryList',
    GET_MEDIA_PLAN_CALENDAR_SUMMARY_LIST: '/Planning/GetMediaPlanCalendarSummaryList',
    GET_SCHEDULESLIST_BY_INVENTORYID: '/Planning/GetSchedulesListByInventory',
    UPD_SCHEDULE_UNITS_INFO: '/Planning/UpdateScheduleUnitInfo',
    CONFIRM_CAMPAIGN_MEDIA_PLAN: '/Planning/ConfirmCampaignMediaPlan',
    GET_ISCIs_BY_CAMPAIGN_ID: '/Planning/GetISCIsForCampaign',
    GET_SCHEDULESLIST_BY_CAMP_MEDIA_PLANID: '/Planning/GetSchedulesByCampaignOrMediaPlanId',

    //Sales Media Planning
    SAVE_SALES_MEDIA_PLAN_AND_UNITS: '/Planning/SaveSalesMediaPlanDataAndProposedUnits',
    UPD_SALES_SCHEDULE_UNITS_INFO: '/Planning/UpdateSalesScheduleUnitInfo',
    CONFIRM_SALES_MEDIA_PLAN: (id) => `/Planning/ConfirmSalesMediaPlan?mediaPlanId=${id}`,
    CHANGE_SALES_MEDIA_PLAN_UNITS_STATUS: (id, status, username) => `/Planning/ChangeSalesMediaPlanUnitsStatus?mediaPlanId=${id}&statusId=${status}&modifiedBy=${username}`,

    //Digital Planning
    SAVE_DIGITAL_MEDIA_PLAN_DETAILS: '/Planning/SaveDigitalMediaPlanData',
    GET_DAY_WISE_IMPRESSIONS: '/Planning/GetDayWiseImpressions',
    GET_IMPRESSIONS_SUMMARY: '/Planning/GetImpressionsSummary',

    //Reports
    GET_REPORTS_LIST: '/Reports/GetReportsList',
    GET_REPORTS_CONFIG: (moduleId) =>`/Reports/GetReportCofigurationData?moduleId=${moduleId}`,

    // Plan Copy
    Get_Copy_Plan_Schedules: (leagueId,planTypeId, marketTypeId) => `/PlanCopy/GetPlannedSchedule?leagueId=${leagueId}&planType=${planTypeId}&marketTYpeId=${marketTypeId}`,
    Get_Copy_Plan_Schedules_List: '/PlanCopy/GetPlannedScheduleList',
    Get_Planned_Units:(scheduleId,planType,isROS) => `/PlanCopy/GetPlannedUnit?scheduleId=${scheduleId}&planType=${planType}&isROS=${isROS}`,
    Get_Filtered_Schedules:`/PlanCopy/GetCopyPlanScheduleSearch`,
    SAVE_COPY_PLAN_SCHEDULE_DATA: '/PlanCopy/SaveCopyPlanScheduleData',

    // Reconciliation
    VALIDATE_FILE: `/Reconcilliation/UploadFile`,
    UPLOAD_DATA: '/Reconcilliation/SaveReconciliationData',
    GET_RECONCILIATION_LIST: (leagueId) => `/Reconcilliation/GetLinearReconciliation?leagueId=${leagueId}`,
    SAVE_RECONCILIATION_DATA: `/Reconcilliation/SaveLinearReconciliation`,
    //TeamIdentity API
    GET_EMP_DETAILS: (emailId) => `https://teamdirectoryapi.nba.com/api/UserProfileData?email=${emailId}`,
    GET_EMP_PROFILE_PIC: (id)  => `https://teamdirectoryapi.nba.com/api/ProfileImageData?id=${id}`
}

export default APIURLConstants;