export const APP_MESSAGE ={
    Date_Validation: 'The end date should be greater than or equal to the start date.',
    Require_Field_Validation: 'Please select __FieldName__.',
    Require_Text_Field_validation: '__FieldName__ is a required field.',
    Filter_Delete: 'Filter Deleted!',
    Filter_Save: 'Filter Saved !',
    Split_Schedule_Unit: 'Selected Unit splitted successfully.',
    Split_Unit_Validation: 'Sum of count is not equal to Orginal size __value__.',
    Merge_Schedule_Unit: 'Selected Units are merged successfully.',
    Unavailable_Unit: 'Unit Size not exist. Available unit Sizes are __availSizes__.',
    End_Date_Validation: 'Date should be less than or equal to Filter Criteria EndDate.',
    Start_Date_Validation: 'Date should be greater than or equal to Filter Criteria StartDate.',
    API_Error: 'Something went wrong.',
    API_Success: 'Data saved successfully.',
    API_Schedule_Copy_Success: 'Schedule breakup data copied successfully..!',
    Server_Error: 'Server error.',
    Media_Plan_Validation: "Same Media Plan already assigned to same spot.",
    Unavailable_Spots: "No spot left to assign selected media plan.",
    Spot_Status: "All the spots are Pending Confirm/Confirmed/Trafficked.",
    Spot_Status_Err: "Selected spot already __Status__.",
    Spot_Assigned_Err: "Selected spot assigned to another Campaign.",
    Unable_To_Assign_Campaign: "Can't assign the Campaign to already assigned Sales Unit.",
    Impressions_or_Percentage_Validation: "Please enter either Impressions or Percentage.",
    AvailableUnits_Validation: "Please enter lessthan or equal to AvailableUnits.",
    Invalid_Value: 'Please enter valid value.',
    Episode_Unit_Rule: 'Please enter Units Per Episode OR Units/Distribution Rule.',
    Greater_Exist_AvailableUnits: 'Please enter value(s) lessthan or equal to AvailableUnits.',
    Selected_Episode_Value: 'Please enter value(s) for the selected episode(s).',
    Checkbox_selection: 'Please select at least one checkbox.',
    Unit_Validation: 'Please enter Units first.',
    Episode_Length_msg: 'Enter Units per Episode lessthan or equal to available units for each Episode.',
    Assign_Unit_Validation: 'Sum of available units is lessthan the units entered.',
    Split_Unit_Data_Issue: 'There is some issue with the __Field__ data',
    Unit_Count_Req_Validation: 'Please add Unit Count',
    Unit_Count_Validation: 'Unit Count value cannot be less than 1',
    Season_Date_Validation: 'Make sure start date and end date falls between season start date and season end date.',
    Confirm_Unit_Warning: 'Make sure you have added some units before clicking Confirm.',
    Unavailable_Inventory_Item: "Inventory Item not found in list..!",
    Notification_Err: "Opps there was an error. Please retry..!",
    No_Schedule_Breakup: 'No schedule breakupss found for selected inventory list item.',
    Quantity_To_Validation: "The value of `Quantity To` should not be less than `Quantity From`.",
    Mandatory_Fields: 'Please add mandatory fields',
    Edit_Mode: "Already open in edit mode.",
    Project_Count_validation: "Total should not be greater than projected count.",
    Create_ISCI_Success: "ISCI created successfully.",
    Update_ISCI_Success: "ISCI updated successfully.",
    Linear_Sales_Count_Validation:'Please enter sales unit count in multiples of 5',
    Not_Yet_Available: "Not yet available.",
    Linear_Ins_Count_Validation:'Please enter institutional unit count in multiples of 5',
    Invalid_Upload: 'Uploaded file is not valid.',
    No_data_to_Upload: "No data to upload.",
    Invalid_Reconcile: "Please check below data. It is not properly reconcile",
    Valid_Upload: 'Uploaded file is valid.'
}