
//Sample Action constants for reference
export const ADD_SCHEDULE = 'SCHEDULE/SCHEDULE_TABLE/ADD_SCHEDULE'
export const UPDATE_SCHEDULE = 'SCHEDULE/SCHEDULE_TABLE/UPDATE_SCHEDULE'
export const DELETE_SCHEDULE = 'SCHEDULE/SCHEDULE_TABLE/DELETE_SCHEDULE'